---
title: "Week6Assignment"
author: "Ashwin Thota"
date: "June 18, 2017"
output:
  html_document: default
  pdf_document: default
---


```{r}
# read csv file
bk <- read.csv("https://raw.githubusercontent.com/AshwinThotaDS/Week6/master/Data/rollingsales_statenisland.csv",skip=4,header=TRUE)
```

```{r}
## Check the data
head(bk)
summary(bk)
str(bk) # Very handy function!
#Compactly display the internal structure of an R object.
```

```{r}
## clean/format the data with regular expressions
## More on these later. For now, know that the
## pattern "[^[:digit:]]" refers to members of the variable name that
## start with digits. We use the gsub command to replace them with a blank space.
# We create a new variable that is a "clean' version of sale.price.
# And sale.price.n is numeric, not a factor.
library(plyr)
bk$SALE.PRICE.N <- as.numeric(gsub("[^[:digit:]]","", bk$SALE.PRICE))
count(is.na(bk$SALE.PRICE.N))
names(bk) <- tolower(names(bk)) # make all variable names lower case
```
```{r}
bk$gross.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$gross.square.feet))
bk$land.sqft <- as.numeric(gsub("[^[:digit:]]","", bk$land.square.feet))
bk$year.built <- as.numeric(as.character(bk$year.built))
```

```{r}
## do a bit of exploration to make sure there's not anything
## weird going on with sale prices
attach(bk)
hist(sale.price.n) 
detach(bk)
```
```{r}
## keep only the actual sales

bk.sale <- bk[bk$sale.price.n!=0,]
plot(bk.sale$gross.sqft,bk.sale$sale.price.n)
plot(log10(bk.sale$gross.sqft),log10(bk.sale$sale.price.n))

```

